MODEL_NAME: "google/gemma-3-270m"

# data
SFT_POST_FRAC: 0.1275
RM_POST_FRAC: 0.4530
PPO_POST_FRAC: 0.4195

SFT_TRAIN_FRAC: 0.885
RM_TRAIN_FRAC: 0.650
PPO_TRAIN_FRAC: 0.658

SEED: 42


# train sft
SFT_EPOCHS: 5
SFT_BATCH: 8
SFT_ADAM_BETA1: 0.9
SFT_ADAM_BETA2: 0.95
SFT_LR_DECAY: 0.1
SFT_RESIDUAL: 0.2
SFT_LR: 0.000005
SFT_SAVE_PATH: sft_checkpoints/

