#training params
TOTAL_ITERS: 1000000000
LOG_EVERY: 100
SAVE_EVERY: 10000
Q1_FCN_SAVE_PATH: checkpoints/sac_drone_q1.pt
Q2_FCN_SAVE_PATH: checkpoints/sac_drone_q2.pt
VALUE_FCN_SAVE_PATH: checkpoints/sac_drone_v.pt
VALUE_TARGET_FCN_SAVE_PATH: checkpoints/sac_drone_vt.pt
POLICY_FCN_SAVE_PATH: checkpoints/sac_drone_p.pt

# env params
TOTAL_AGENTS: 16384

#sac
TAU: 0.005
# TARGET_UPDATE: 1000
TARGET_GRAD_STEPS: 4
REWARD_SCALE: 5

#model params
HIDDEN_SIZE: 256
LOG_STD_MIN: -20
LOG_STD_MAX: 2

#other
LR: 0.0003
GAMMA: 0.99
BUFFER_SIZE: 1000000
MINIBATCH: 1024


