#training params
TOTAL_ITERS: 50000000
LOG_EVERY: 10
SAVE_EVERY: 500
POLICY_FCN_SAVE_PATH: checkpoints/a2c_breakout_p.pt
VALUE_FCN_SAVE_PATH: checkpoints/a2c_breakout_v.pt


# env params
TOTAL_AGENTS: 1024

#a2c
T_MAX: 5

#model params
HIDDEN_SIZE: 256

#optimization
LR: 0.0007
ENTROPY_COEF: 0.01
GAMMA: 0.99