#training params
TOTAL_ITERS: 320000000
LOG_EVERY: 10
SAVE_EVERY: 500
SAVE_PATH: checkpoints/pong_ppo.pt

# env params
TOTAL_AGENTS: 256

#ppo rollout and update
HORIZON: 128
EPOCHS: 3
MINIBATCH: 8192

#ppo params
EPS_ALPHA: 0.1
C1: 1
C2: 0.01

#model params
HIDDEN_SIZE: 64

#gae
LAMBDA: 0.95
GAMMA: 0.99

#optimization hyperparams
ALPHA: 1.0
ALPHA_END: 0.0
ADAM_ALPHA: 0.00025